// Generated by https://quicktype.io

import {Word} from './quran-pager.types';

export namespace APITypes {
  export interface Verse {
    id: number;
    verse_key: string;
    text_uthmani: string;
  }
  // Generated by https://quicktype.io

  export interface VerseInfo {
    verse_key: string;
    id: number;
    verse_number: number;
    hizb_number: number;
    rub_el_hizb_number: number;
    ruku_number: number;
    manzil_number: number;
    sajdah_number: number;
    page_number: number;
    juz_number: number;
    words: Word[];
  }

  export interface Chapter {
    id: number;
    revelation_place: string;
    revelation_order: number;
    bismillah_pre: boolean;
    name_simple: string;
    name_complex: string;
    name_arabic: string;
    verses_count: number;
    pages: number[];
    translated_name: TranslatedName;
  }
}

interface TranslatedName {
  language_name: string;
  name: string;
}

// Verse and Word types are now exported from quran-pager.types.ts
// These types are kept here for API response structure only
// Use types from quran-pager.types.ts for component usage

export interface Translation {
  text: null | string;
  language_name: LanguageName;
}

export enum LanguageName {
  English = 'english',
}
