// Generated by https://quicktype.io

export interface VerseAPI {
  id: number;
  verse_key: string;
  text_uthmani: string;
}
// Generated by https://quicktype.io

export interface VerseInfoAPI {
  verse_key: string;
  id: number;
  verse_number: number;
  hizb_number: number;
  rub_el_hizb_number: number;
  ruku_number: number;
  manzil_number: number;
  sajdah_number: number;
  page_number: number;
  juz_number: number;
  words: Word[];
}

export interface Verse extends VerseInfoAPI {}

export interface Word {
  char_type_name: 'word' | 'end';
  code_v1: string;
  text: string;
  id: number;
  position: number;
  page_number: number;
  line_number: number;
  audio_url: null | string;
  translation: Translation;
  transliteration: Translation;
}

export interface Translation {
  text: null | string;
  language_name: LanguageName;
}

export enum LanguageName {
  English = 'english',
}
